### ISSUE TITLE
Navigation bug after changing preferences

### ISSUE THREAD

**Issue by AnneloreVB** [Qrivi/PlutusAndroid#1]
In the app, going to Settings, changing the app's language then setting the home screen makes the app always jump back to Settings when going back from a transaction detail.

**Steps to reproduce:**
- Open app
- Navigate to Settings
- Set another language
- Set another screen as startup screen
- Navigate to transactions
- Click a transaction to open its details
- Hit phone's or app's back button 

**Expected:**
App jumps back to transaction list

**What actually happens:**
App jumps back to settings screen

**Comment by Qrivi** [comment]
Thanks for reporting this, @AnneloreVB! 

We'll be looking into this as soon as school grants us some free time. ;)

**Comment by Qrivi** [comment]
Big thanks for looking into this so quickly, @DavidOpDeBeeck! Looks fine now!
